version: '3.8'
services:
  # Servicio PostgreSQL con extensión PGVector
  postgres:
    image: ankane/pgvector:v0.2.0 # ¡Asegúrate que esta es la imagen!
    environment:
      POSTGRES_DB: crypto_rag_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio LocalStack para simular AWS S3
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

# Volúmenes para persistencia de datos
volumes:
  postgres_data:
  localstack_data: